LOCATION_TYPES = {
    'REGIONAL': 'REGIONAL',
    'ZONAL': 'ZONAL',
} 

REGION_LOCATION_TO_ACRONYM = {
    'us-central1': 'io',
    'us-west2': 'la',
    'us-west1': 'ore',
    'us-east4': 'nv',
    'us-east1': 'sc',
    'northamerica-northeast1': 'mtreal',
    'southamerica-east1': 'spaulo',
    'europe-west1': 'eu',
    'europe-north1': 'fi',
    'europe-west3': 'ffurt',
    'europe-west2': 'lon',
    'europe-west4': 'nether',
    'asia-south1': 'mbai',
    'asia-southeast1': 'sg',
    'australia-southeast1': 'syd',
    'asia-east2': 'hk',
    'asia-east1': 'tw',
    'asia-northeast1': 'ja',
}

REGION_ACRONYM_TO_LOCATION = {
      'io': 'us-central1',
      'la': 'us-west2',
      'ore': 'us-west1',
      'nv': 'us-east4',
      'sc': 'us-east1',
      'mtreal': 'northamerica-northeast1',
      'spaulo': 'southamerica-east1',
      'eu': 'europe-west1',
      'fi': 'europe-north1',
      'ffurt': 'europe-west3',
      'lon': 'europe-west2',
      'nether': 'europe-west4',
      'mbai': 'asia-south1',
      'sg': 'asia-southeast1',
      'syd': 'australia-southeast1',
      'hk': 'asia-east2',
      'tw': 'asia-east1',
      'ja': 'asia-northeast1',
}

REGION_ACRONYM_TO_HR_LOCATION = {
      'io': 'Iowa',
      'la': 'Los Angeles',
      'ore': 'Oregon',
      'nv': 'Northern Virginia',
      'sc': 'South Carolina',
      'mtreal': 'Montréal',
      'spaulo': 'São Paulo',
      'eu': 'Belgium',
      'fi': 'Finland',
      'ffurt': 'Frankfurt',
      'lon': 'London',
      'nether': 'Netherlands',
      'mbai': 'Mumbai',
      'sg': 'Singapore',
      'syd': 'Sydney',
      'hk': 'Hong Kong',
      'tw': 'Taiwan',
      'ja': 'Tokyo',
}

REGION_ACRONYM_TO_COMBINED_LOCATION = {
      'io': 'Iowa (us-central1)',
      'la': 'Los Angeles (us-west2)',
      'ore': 'Oregon (us-west1)',
      'nv': 'Northern Virginia (us-east4)',
      'sc': 'South Carolina (us-east1)',
      'mtreal': 'Montréal (northamerica-northeast1)',
      'spaulo': 'São Paulo (southamerica-east1)',
      'eu': 'Belgium (europe-west1)',
      'fi': 'Finland (europe-north1)',
      'ffurt': 'Frankfurt (europe-west3)',
      'lon': 'London (europe-west2)',
      'nether': 'Netherlands (europe-west4)',
      'mbai': 'Mumbai (asia-south1)',
      'sg': 'Singapore (asia-southeast1)',
      'syd': 'Sydney (australia-southeast1)',
      'hk': 'Hong Kong (asia-east2)',
      'tw': 'Taiwan (asia-east1)',
      'ja': 'Tokyo (asia-northeast1)',
}